pipeline {
    agent any
    parameters {
        choice (
            choices: ['apply','destroy'],
            description: 'terraform choice',
            name: 'SELECT_CHOICE'
        )
    
    }
    stages {
        stage('terraform init') {
            steps {
                dir('/Users/tugbayildirim/terraform_project/root_module/vpc') {
                    echo "Running terraform init"
                    sh 'terraform init -upgrade'
                }
            }
        }

        
    }
}